{{- if .Values.isJob -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: job-script-{{ include "spring-demo.fullname" . }}
data:
  script.sh: {{ range .Files.Lines .Values.scriptPath }}
    {{ . }}{{ end }}
{{- end }}

---
{{- if .Values.isJob -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dind-storage-{{ include "spring-demo.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 10Gi
{{- end }}
